site:
  title: Antwort
  url: https://antwort-dev.github.io
  start_page: antwort::index.adoc

content:
  sources:
    - url: https://github.com/antwort-dev/antwort.git
      branches: main
      start_path: docs

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./supplemental-ui

output:
  dir: ./dist/docs
